version: "3.7"
services:
  Full2020-94899:
    container_name: Full2020-94899
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=alla
      - MYSQL_DATABASE=product
      - MYSQL_USER=ashtokal
      - MYSQL_PASSWORD=alla
    networks:
      Bridge-Zadanie-1:
        ipv4_address: 10.0.10.3
  my-container:
    container_name: my-container
    image: shtokala/product
    ports:
      - 8080:8080
    restart: always
    depends_on:
      - Full2020-94899
    networks:
      Bridge-Zadanie-1:
        ipv4_address: 10.0.10.4
networks:
  Bridge-Zadanie-1:
    driver: bridge
    ipam:
        config:
            - subnet: 10.0.10.0/24


